[package]
name = "fncalc-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
fncalc = { path = "../fncalc" }
rustyline = "12.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
